# Gruvbox dark
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[font]
normal = { family = "UbuntuMonoNerdFont", style = "Regular" }
size = 16

[keyboard]
bindings = [
    { key = "Enter", mods = "Control", action = "ToggleFullscreen" },
    { key = "F11", action = "ToggleFullscreen" },
]

[terminal]
shell = { program = "/bin/fish", args = [ "--login" ] }

[window]
dimensions = { columns = 140, lines = 40 }
position = { x = 240, y = 200 }

